### ISSUE TITLE
0.3 release schedule?

### ISSUE THREAD

**Issue by fosskers** [dylemma/xml-spac#10]
Any thoughts on this? I'd like to release a library that depends on 0.3.

**Comment by dylemma** [comment]
Hey, I'm glad to hear there's still interest in this. It's been some time since I've worked on this, but I had started making progress on #3 and incidentally #2. IIRC there was a bit of work left (mostly docs) but I should be able to put out a release with those changes. Sometime this week, optimistically speaking.

**Comment by fosskers** [comment]
Awesome! Thanks for the response.

**Comment by dylemma** [comment]
Version 0.3 is released, and should be appearing on maven central soon.

**Comment by fosskers** [comment]
<3 <3 <3
