### ISSUE TITLE
Perform parsing in parallel

### ISSUE THREAD

**Issue by luis3m** [dylemma/xml-spac#15]
I'm wondering if it's possible to perform XML parsing in parallel or how hard would it be to implement this feature in this library. What are your thoughts on that?

```Scala
Splitter(matcher)
  .through(parser)
  .onParallel(10)
  .consumeToList
  .consume(input)
```

Something as above where 10 threads are running in parallel to process all entries. Does this make sense?

**Comment by dylemma** [comment]
Currently the library doesn't have a means of handling async - it's something I'd eventually like to add, and I think it'll ultimately be necessary if I want to integrate with the popular scala streaming libraries.

If I'm understanding your request correctly, you want each "substream" identified by the splitter to be handled on a separate thread(pool)? Is `parser` something that blocks or is somehow slower than the input?

**Comment by dylemma** [comment]
I'm thinking that since `.onParallel` would effectively upgrade the whole pipeline to "async", the `consume` method would return a `Future[List[T]]` rather than a simple `List[T]`, or else it would have to block on the parallel executions finishing, which isn't something I want to do at the library level.

Just thinking out loud...
Currently the `Handler` class returns `Option[T]` to signal the handler's completion state, but to handle async, I'd need an ADT like `Option[T] | Future[Option[T]]` to signal "ready for more", "done", or "I'll tell you later". I'm not sure if this is a direction I want to take the library.... instead it might be better to get to a point where a Transformer can be plugged into something like FS2 as a `Pipe[F, I, O]`. I believe the `.mapAsyncUnordered` method in FS2 accomplishes what you want here.

**Comment by dylemma** [comment]
Recently I've been toying with the idea of integrating with Cats/Monix and adding an `F[_]` type parameter to Parser/Handlers. If this became a reality, `Parser[In, Out]` would become a `Iterant[F, In] => F[Out]` and `Transformer[A, B]` would become a `Iterant[F, A] => Iterant[F, B]`

**Comment by burakkose** [comment]
FS2 integration would be really useful. It naturally brings effect system with the integration, so people could integrate to their IO applications. There are even libraries that allow people to convert their FS2 streams into Akka Streams and Apache Camel.

**Comment by dylemma** [comment]
Agreed, though what I want most is a way to somehow support both FS2 Streams and Monix Iterants via some abstraction from Cats. I've got more experience with Monix from my job, but it seems like FS2 has a lot of traction in the community.

**Comment by dylemma** [comment]
Just popping in to say I haven't forgotten about this, but just haven't gotten around to doing any work on this project lately. I did have a fairly robust PoC of the library that uses a pure functional style under the hood and lends itself well to being adapted to either a fs2.Pipe or an Iterant=>Iterant function. I'll try to get back to this in the near future and at least push my prototype code to a branch.

**Comment by dylemma** [comment]
As of merging #27 I'm considering this done!

I ended up deciding to add FS2 as a dependency to the core library, rather than try to come up with some new generic representation of a `Stream` and have to provide conversions to and from that representation.

Rough overview of the new features:

- `Transformer` and `Parser` both get `.toPipe[F]`
- A `Parser` can now `.parseF` a `Stream[F, In]` to get a `F[Out]`
- In addition to the usual things a `Parser` can `.parse`, it can now also `.parse` a `Stream[SyncIO, In]` to get an `Out`
- `JavaxSource` and `JacksonSource` have apply methods for constructing `Stream[F, *]` for `XmlEvent` and `JsonEvent` respectively

This will be released with 0.9 once everything else settled.

**Comment by mrdziuban** [comment]
@dylemma thanks for all your work on this library! I came searching for a way to parse in parallel and I'm wondering how to take advantage of it with FS2. If I have a `Transformer` like in the readme, how can I use it to parse `Post`s in parallel?

```scala
val rawXmlBytes: Stream[IO, Bytes] = ...
val xmlStream: Stream[IO, XmlEvent] = Fs2DataSource.fromRawXmlStream(rawXmlBytes)
// As far as I can tell, this parsing doesn't happen in parallel
val postsStream: Stream[IO, Post] = xmlStream.through(Splitter.xml("blog" \ "post").as[Post])
```

I'm hesitant to use `parseF` because I want to take advantage of the laziness of the `Stream` and not pull all `Post`s into memory. Do you have any suggestions?

**Comment by dylemma** [comment]
When you say "parse Posts in parallel", I think that could mean one of two things:

1. You want to parallelize the processing of the underlying XmlEvents, having Spac itself run on multiple threads within the scope of the given Transformer. This is not supported by Spac. If the event-handling logic were to try to handle events in an arbitrary/parallel order, the structure of the document wouldn't make sense to it. Spac needs to receive and handle the events sequentially.
2. You want to consume the parsed `Post`s in parallel, i.e. your downstream logic will operate on many threads. This is possible, e.g. with fs2's `Stream#mapAsyncUnordered` as I mentioned earlier in this thread.

Even though a Spac Transformer can't run in parallel with itself as with point 1 above, it *is* still lazy. To slightly correct your example above:
```scala
val postsStream: Stream[IO, Post] = xmlStream.through(Splitter.xml("blog" \ "post").as[Post].toPipe[IO])
```
You can see the underlying implementation of `toPipe` [here](https://github.com/dylemma/xml-spac/blob/main/core-fs2/src/main/scala/io/dylemma/spac/interop/fs2/impl/TransformerToPipe.scala). As you can see, the pipe will "pull" the next chunk of data from the stream, pass it to the transformer's handler, and emit any output generated by the transformer at that step. It does not collect the entire contents of either the input stream nor output stream at any given time.

As an example of handling the Posts in parallel, you could do:
```scala
def handlePost(post: Post): IO[Unit] = 
  IO.sleep(3.seconds) >> IO.println(s"I handled $post")

val handlePostsInParallel: IO[Unit] = postsStream
 .mapAsyncUnordered(3)(handlePost)
 .compile
 .drain
```

**Comment by mrdziuban** [comment]
I was indeed referring to point 1 -- processing the underlying events in parallel -- but I understand why it's not possible. I'll stick to the parallel downstream processing. Thanks for the input!
