### ISSUE TITLE
Matching based on sibling elements

### ISSUE THREAD

**Issue by ramonmaruko** [dylemma/xml-spac#20]
This is question rather than an issue.

GIven the following document:

```xml
<foo>
  <bar>
    <kind value="1"/>
    <text>1</text>
  </bar>
  <bar>
    <kind value="2"/>
    <text>2</text>
  </bar>
</foo>
```

Is it possible to only split/match on `<bar>` elements with a `kind` of `2`? I've tried doing a:

```scala
def isKindMatcher(id: String) = SingleElementContextMatcher.predicate("", { e =>
  e.getName.getLocalPart == "kind" &&
    Option(e.getAttributeByName(new QName("value"))).fold(false)(_.getValue == id)
  })

XMLSplitter(* \ "foo" \ "bar" \ (isKindMatcher("2") & "text")).firstOption.asText
```

But it's returning `None`.

**Comment by dylemma** [comment]
ContextMatcher doesn't have sibling-match capability, since it's really oriented around the "stack" of nested elements. But this seems like a decent use-case for the `followedBy` feature of Parsers.

```scala
// make parsers for <kind> and <text> from the perspective of the <bar> element
val kindParser = XMLSplitter(* \ "kind").first.attr("value")
val textParser = XMLSplitter(* \ "text").first.asText

// make a parser for the <bar> element by combining the two above
val barParser = kindParser.followedBy {
  // this is effectively how you'd filter the kinds. Map matches to Some, others to None
  case "2" => textParser.map(Some(_))
  case _ => Parser.constant(None)
}

// create a parser for the stream of <bar> elements from the perspective of the <foo> element
val fooParser = XMLSplitter("foo" \ "bar")
  .map(barParser) // at this point we'll have a stream of Option[String]
  .collect { case Some(text) => text } // ignore the `None`s from barParser
  .parseFirstOption // and stop once we get one

fooParser.parse(xml) // Some(2)
```

Extra reading:
 - [another example of `followedBy`](https://github.com/dylemma/xml-spac/blob/master/examples/src/main/scala/io/dylemma/xml/example/Example5_FollowedBy.scala)
 - [how to deal with optional elements that need to be followed](https://github.com/dylemma/xml-spac/blob/master/examples/src/main/scala/io/dylemma/xml/example/Example7_Interrupter.scala)

Also note:
 - In the splitter example you gave, `* \ "foo" \ ...`, you'd want to remove the leading `*` since the top-level element is `foo`.
 - You can use the `attr(String)` method (from ContextMatcherSyntax) to avoid defining your own matcher based on attributes. There's also a version for QNames.

**Comment by dylemma** [comment]
I started thinking about an alternate approach to ContextMatchers to fit with #14, and I think I can fit your use-case into what I'm imagining... no promises on that being implemented any time soon though.
