### ISSUE TITLE
Tutorial doesn't match `0.2` api

### ISSUE THREAD

**Issue by fosskers** [dylemma/xml-spac#8]
Just a heads-up that `and` syntax for Parsers doesn't work with `0.2` code, and `0.2` is what is advertised in your README.

Everything works fine if I clone your repo and do a `publishLocal` of `0.3-SNAPSHOT`.

**Comment by dylemma** [comment]
Thanks for the heads-up. This is because of #5... I guess I'll have to move to using "development branches" so the master readme stays in sync with the latest maven release. I'll try and get this fixed up sometime tonight

**Comment by dylemma** [comment]
I wanted to avoid rewriting history (which ironically I failed at by force-pushing a correction to my commit) by moving my last several commits to a "dev" branch. For now, I've just added a little note near the "Get it!" section and on the tutorial, linking back to the v0.2 readme.

Going forward I'll try to figure out a way to keep the master readme in sync with the latest release. I'm not 100% sold on using dev branches to accomplish this, mostly because it'd make my project look dead in github's "pulse" view. Maybe for the next release I'll create a dedicated "docs" site.

**Comment by fosskers** [comment]
Does pulse not track commits made on side branches? I thought it did.

**Comment by dylemma** [comment]
Ah my mistake, I guess it does show up. I had pushed some stuff elsewhere and didn't see it on "pulse" until now.

**Comment by fosskers** [comment]
Cool. Anyway, for now I'm using a locally published `0.3-SNAPSHOT` and it's working really well. `xml-spac` exposes something *very* close to the applicative pattern (as emulated also in `scala-parser-combinators`) so it's nice to use.

**Comment by dylemma** [comment]
Glad to hear! If I may ask, how/where did you find out about this project?
